spring:
  datasource:
    url: jdbc:postgresql://localhost:5432?product
    username: postgres
    password: ajiboye
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
application:
    config:
      customer-url: http://localhost:8222/api/customer
      payment-url: http://localhost:8222/api/payment
      product-url: http://localhost:8222/api/product

server:
  port: 9595