spring:
  data:
    mongodb:
      username: ajiboye
      password: ajiboye
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8383