#Services needed for the application
services:
  postgres:
    container_name: micro-service_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ajiboye
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-ajiboye}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_CONFIG_SERVER_MODE: "false"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5151:80"
    networks:
      - microservices-network
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ajiboye
      MONGO_INITDB_ROOT_PASSWORD: ajiboye
    networks:
      - microservices-network

  mongo-express:
    image: mongo-express
    container_name: ms_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ajiboye
      ME_CONFIG_MONGODB_ADMINPASSWORD: ajiboye
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - microservices-network

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices-network

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
